// <auto-generated />
using DogApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DogApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DogApi.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Tail_length")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "red & amber",
                            Name = "Neo",
                            Tail_length = 22,
                            Weight = 32
                        },
                        new
                        {
                            Id = 2,
                            Color = "white & amber",
                            Name = "Geo",
                            Tail_length = 40,
                            Weight = 20
                        },
                        new
                        {
                            Id = 3,
                            Color = "black & white",
                            Name = "Rio",
                            Tail_length = 28,
                            Weight = 37
                        },
                        new
                        {
                            Id = 4,
                            Color = "white",
                            Name = "Dj",
                            Tail_length = 10,
                            Weight = 19
                        },
                        new
                        {
                            Id = 5,
                            Color = "black",
                            Name = "Jessy",
                            Tail_length = 17,
                            Weight = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = "gray",
                            Name = "Dory",
                            Tail_length = 12,
                            Weight = 16
                        },
                        new
                        {
                            Id = 7,
                            Color = "gold",
                            Name = "Nora",
                            Tail_length = 32,
                            Weight = 30
                        },
                        new
                        {
                            Id = 8,
                            Color = "gray & white",
                            Name = "Pedro",
                            Tail_length = 47,
                            Weight = 4
                        },
                        new
                        {
                            Id = 9,
                            Color = "yellow",
                            Name = "Pongo",
                            Tail_length = 37,
                            Weight = 16
                        },
                        new
                        {
                            Id = 10,
                            Color = "white",
                            Name = "Z",
                            Tail_length = 47,
                            Weight = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
